name: Music Radio Continious Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    name: Running lint test
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: caching and restoring the gradle
        uses: actions/setup-java@v2
        with:
         distribution: temurin
         java-version: 17
         cache: gradle

      - name: giving permission
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lint

      - name: upload html test rport
        uses: actions/upload-artifact@v3
        with:
          name: lintReport.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    name: Running unit test
    needs: [ lint-test ]
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: caching and restoring the gradle
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: giving permission
        run: chmod +x gradlew

      - name: run tests
        run: ./gradlew test

      - name: upload the test report
        uses: actions/upload-artifact@v2
        with:
            name: unit test report
            path: app/build/reports/tests/testDebugUnitTest/

  build-verification:
      name: Verifying the build
      needs: [ lint-test, unit-test ]
      runs-on: ubuntu-latest
      steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: caching and restoring the gradle
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: giving permission
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Music-Radio.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  success:
        needs: [ lint-test, unit-test, build-verification ]
        runs-on: ubuntu-latest
        steps:
          - run: echo Success!
