name: Music Radio CICD

#mentioning on what the action should trigger
on: pull_request

jobs:
  lint-test:
    #Mentioning on which os the repo should checkout to run
    runs-on: ubuntu-latest
    #This is checking out the repo on ubuntu to run futhur steps
    steps:
      - uses: actions/checkout@v3
      #The lint tool checks your Android project source files for potential bugs and optimization improvements for correctness, security, performance, usability, accessibility, and internationalization
      - name: giving permission
        run: chmod +x gradlew
      
      - name: Run Lint
        run: ./gradlew lint
      #Making and uploading the report in html form
      - name: upload html test rport
        uses: actions/upload-artifact@v3
        with:
          name: lintReport.html
          path: app/build/reports/lint-results-debug.html

  #this is to run the unit test cases
  unit-test:
    needs: [ lint-test ]
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: giving permission
        run: chmod +x gradlew

      - name: run tests
        run: ./gradlew test

      - name: upload the test report
        uses: actions/upload-artifact@v2
        with:
            name: unit test report
            path: app/build/reports/tests/testDebugUnitTest/

  #setting up env to run and building apk
  build-verification:
      needs: [ lint-test, unit-test ]
      runs-on: ubuntu-latest
      steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: giving permission
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Music-Radio.apk
          path: app/build/outputs/apk/debug/music-radio-debug.apk

  success:
        needs: [ lint-test, unit-test, build-verification ]
        runs-on: ubuntu-latest
        steps:
          - run: echo Success!
