
  name: ANdroid Build


  on: pull_request

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1

        - name: set up jdk
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: giving permission
          run: chmod +x gradlew

        - name: Run Tests
          run: ./gradlew test

        - name: Build project
          run: ./gradlew assemble




