name: Music Radio Continious Development

on:
  push:
    branches: [ master ]

jobs:
  generate_build:
    name: Generating Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: caching and restoring the gradle
        uses: actions/setup-java@v2
        with:
         distribution: temurin
         java-version: 17
         cache: gradle

      - name: Bump Version Code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: giving permission
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Music-Radio.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  distribute_build:
    needs: [ Generate_build ]
    name: Distributing build on Firebase and Microsoft team
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: connected
          file: app/build/outputs/apk/debug/app-debug.apk

      - name: Notify Team of Build Status
        if: always()
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          job: ${{ toJson(job) }}

  success:
    needs: [ Generate_build, Distribute_build ]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success!